### ISSUE TITLE
giving error for mp3 audio files

### ISSUE THREAD

**Issue by sushien** [keunwoochoi/UrbanSound8K-preprocessing#1]
hi,
why the audio length should be less than 4 seconds and will this work for MP3 files?

**Comment by keunwoochoi** [comment]
Because that's how the dataset is made. For some other datasets it doesn't need to be 4s. And it works for mp3 files if your system has mpeg decoder. I use `librosa` to load audio, which uses `audioread`. If you're using linux, try `sudo apt-get install libav-tools `.
